[package]
name = "ferris"
version = "0.1.0"
edition = "2024"

[dependencies]
penrose = { path = "/home/me/Git/penrose"}
penrose_ui = { path = "/home/me/Git/penrose/crates/penrose_ui"}
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
